#!/bin/bash


# sudo cp recordk /usr/local/bin/


# Check if an argument (recording duration) is provided
if [ -z "$1" ]; then
    echo "Usage: record <seconds>"
    exit 1
fi

# Set duration from argument
duration=$1

# Get the first available microphone
mic_device=$(arecord -l | grep -m 1 "card" | awk '{print $2}' | tr -d ':')

if [ -z "$mic_device" ]; then
    echo "No recording device found!"
    exit 1
fi

timestamp=$(date +%H%M)
audio_file="re_$timestamp.wav"
text_file="tx_$timestamp.txt"

record_audio() {
	arecord -D plughw:1,0 -f cd -t wav -d $duration "$wav_output"
}

record_keyboard() {

	old_stty=$(stty -g)

	trap 'stty $old_stty' EXIT

	stty raw -echo

	dd bs=1 if=/dev/stdin of="$text_file" status=none

	stty "$old_stty"
}

record_audio &

echo "Recording audio and keyboard for $duration seconds..."
timeout "$duration" bash -c record_keyboard

wait

echo
echo "Both done"






