#!/bin/bash

# bash wrapper for the grade program

# uses the listen function against every wav file in the current directory
for file in *.wav; do
	echo "Checking file: " "$file"
	python3 listen.py "$file"
done
